### ISSUE TITLE
Enforce a default or existing value when adding a non-nullable field to an existing table

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky_migrator#12]
The idea here is that you have a table with existing data and you want to add a non-nullable column to it. Adding that column without a value to fill it in, or a default value will cause postgres (or whatever database) to throw an error.

The solution would be to require the `add` method inside of an `alter` table statement to have either a default value, or fill value:

```crystal
alter :posts do
  add state : String, default: "draft"
end
```

Since there are already posts in the database, requiring them all to have a `state` would cause postgres to error. This would set a default value like this:

```sql
ALTER TABLE posts (
    state varchar(20) DEFAULT 'draft'
);
```

But sometimes, you don't necessarily want a default, but you do need to supply an existing value:

```crystal
alter :tasks do
  add completed_at : Time, fill_existing_with: Time.new(2017, 11, 2)
end
```

`fill_existing_with` would first create the field as nullable, then run this:

```sql
UPDATE tasks SET completed_at = '2017-11-02';
ALTER TABLE tasks ALTER COLUMN completed_at SET NOT NULL;
```

If either of these keys weren't specified, a compile time error like this would be thrown:

> Adding a required field to an existing table requires you to set a default or use fill_existing_with. Example: add positive : Bool, fill_existing_with: false

**Comment by mikeeus** [comment]
I think this is a good idea. Just a couple things:

1. Users will need both default value and type specific options when altering a table right? In order to do this I'll need to refactor `default_value` and `column_type` from `CreateTableStatement` so they can be used in the `AlterTableStatement`.

@paulcsmith Should I make `DefaultValue...` and `ColumnType...` classes with class methods? Or is there a preferred way to do this? 

2. `fill_existing_with` generates multiple SQL statements, so `AlterTableStatement` will need to be made similar to `CreateTableStatement` and return an array of statements. This also applies if you allow the `index: true` option to alter table. Should I add that option?

**Comment by edwardloveall** [comment]
Here's a workaround for now:

```crystal
class AddStateToPosts::V20171102095010 < LuckyMigrator::Migration::V1
  def migrate
    alter :posts do
      add state : String?
    end

    execute "UPDATE posts SET state = 'published';"
    execute "ALTER TABLE posts ALTER COLUMN state SET NOT NULL;"
  end

  def rollback
    alter :posts do
      remove :state
    end
  end
end
```

**Comment by paulcsmith** [comment]
The last comment sparked the idea for https://github.com/luckyframework/lucky_migrator/issues/50 :D Thanks for sharing.

@mikeeus 1) Yes they would need default value and type-specific options for altering tables as well. Maybe a couple modules like `ColumnDefaultHelpers` and `ColumnTypeOptionHelpers`? I added an issue here: https://github.com/luckyframework/lucky_migrator/issues/51

2) Yes it will need the same changes so it has an array of statements. And yes index: true and unique: true should also work on alter. Thanks for catching that :)
