### ISSUE TITLE
Run a single migration by default

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky_migrator#43]
What does everyone think about running a single migration instead whatever migrations are left to run?

I find that with Rails, if I have multiple migrations pending, about half the time I'm doing code surgery such as a complicated rebase and only want to run a single migration at a time. This is opposed wanting to catch up on all pending migrations that my local copy missed.

The upside is you don't run migrations on accident that might be hard to re-run. The downside is a significant departure from the status quo.

One way to mitigate the problem is to rename the migration command to `lucky db.migrate.one` and add `lucky db.migrate.all`. This would cover all use case and ensure that no one does the wrong thing by accident.

I think in most cases, it will be the same end result because most in most circumstances people will have one migration at a time.

I'm totally willing to be shot down on this, but I'd love to know what people think.

**Comment by mikeeus** [comment]
@edwardloveall I get what you mean about troubleshooting a migration, you're either only interested in one that failed or you want to step through them and tweak them. 

I like the new `lucky db.redo` task for this kind of thing, but it rolls back one then runs all remaining migrations. I was actually thinking that it could be better if it only migrated the next migration, similar to your suggestion.

Personally I still expect `migrate` to run all the remaining migrations, but I would like a `migrate_one/migrate.one` command for troubleshooting and have redo use that instead.

**Comment by edwardloveall** [comment]
Yeah, your PR (#42) is actually what made me think about this. You're probably right that it would be better to match expected behavior.

I did just think about that `rollback` only affects one migration, so that's another reason for `migrate` to mirror it. This is what I think expected behavior would be if there was no historical context. But context is obviously important for adoption.

**Comment by paulcsmith** [comment]
This is a tricky issue because people are used to it migrating everything (as you mentioned). I'm ok making changes to defaults if the gain is big enough, but I think in this case it is about even. The reason I think that is that I often do want to migrate everything. When I first start a project, or if someone merges a PR with a couple migrations. I also tend to only migrate at the end of a rebase.

So I think changing the default might mess with those workflows. With that said, I do see the value in migrating just one migration so I think adding a `lucky db.migrate.one` would be an awesome addition. I'll add an issue for it!

**Comment by paulcsmith** [comment]
Going to close for now. Further discussion can happen in #49
