### ISSUE TITLE
Disallow both `default` *and* `fill_existing_with`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_migrator#64]
https://github.com/luckyframework/lucky_migrator/pull/62/files#r155251819

**Comment by mikeeus** [comment]
Weird, I only saw the "Just making sure you saw this ^" comment and the previous one didn't show up so I didn't know it was a problem.

I allowed both because I misunderstood what default does. But apprently it fills the existing rows with a value *and* makes it the default on the column. So the two settings are redundant.
